### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by nafergo** [dainst/idai-field#11]
- Any chance we can add 3D models?
- any plans for localized versions?
- how can I custom/change/edit the dropdowns and interface?
 
and thx for the linux appimage seems to work flawless ;)

**Comment by danielmarreirosdeoliveira** [comment]
Regarding the editing of configuration files of a downloaded iDAI.field .AppImage. This is how it would work:

From https://github.com/AppImage/AppImageKit/releases download a version of the appimagetool (I took appimagetool-x86_64.AppImage from Release 12) and make it executable. Then, assuming
both .AppImages are located in the same directory, open a terminal, go to that directory, and execute the following commands:

	$ ./iDAI.field-2.18.2-Linux.AppImage --appimage-extract # extract to squashfs-root
	$ vi squashfs-root/resources/config/Library/Language.de.json # edit a config file
	$ ./appimagetool-x86_64.AppImage squashfs-root/ # create a new appimage 
	$ ./iDAI.field-x86_64.AppImage # execute it (note that the name is somewhat different from the original)
	
Altough this is possible, it is clear that it is a uncomfortable way of editing and then seeing those changes, especially while learning about how our configuration files work. At the moment we'd suggest experimenting with downloading the sources from the idai-field repository and building them directly, at it is explained in the README.md.

We are planning to address the issue of making configuration editing more accessible soon in one of the upcoming releases.

**Comment by tkleinke** [comment]
> Any chance we can add 3D models?

Yes, we are planning to add support for 3D models later this year.

> any plans for localized versions?

We already have some localizations: You can switch between an English and a German user interface in the settings menu; an Italian translation of the user interface is currently in the works. There are also translations of many configuration items (field labels, value lists etc.) in Spanish, French and Italian.

**Comment by lsteinmann** [comment]
Hey there, while theres a "questions"-issue like that open I would like to ask something as well... Is there any way of ordering valuelists other than alphabetically? They seem to automatically order either after their variable or after the labels in the relevant translation... And is ordering on the forms itself possible? (Numbering in front of everything seems a bit ugly.) (Or can I possibly just diable the ordering somewhere so that everything appears in the order it is recorded in the json-files?)

**Comment by tkleinke** [comment]
> Hey there, while theres a "questions"-issue like that open I would like to ask something as well... Is there any way of ordering valuelists other than alphabetically? They seem to automatically order either after their variable or after the labels in the relevant translation...

Hi, values are indeed automatically ordered by their translated labels, but you can provide a custom order via the "order" property (like in [this valuelist](https://github.com/dainst/idai-field/blob/master/src/config/Library/Valuelists.json#L1086)).


> And is ordering on the forms itself possible? (Numbering in front of everything seems a bit ugly.) (Or can I possibly just disable the ordering somewhere so that everything appears in the order it is recorded in the json-files?)

You can change the order in which fields appear in the form by editing the configuration file [Order.json](https://github.com/dainst/idai-field/blob/master/src/config/Order.json). What cannot be changed yet is the assignment of fields to field groups (Core, Dimensions etc.), but the order inside a field group is taken from the configuration in Order.json.

**Comment by nafergo** [comment]
> Yes, we are planning to add support for 3D models later this year.

Got excited! sorry to trouble but have additional questions:
- This meaning we can add 3D object for coin (tes project) instead of image?
- This meaning we can actually have a 3D scene for a project instead of 2d top view?

**Comment by tkleinke** [comment]
Our goal for this year is to allow importing 3D models and linking them to resources in the same way it's currently possible with images (with an 3D model viewer instead of an image viewer). We also have a prototype for a 3D project map and hope to integrate that (or something similar) into the app at a later time, but that probably won't happen this year.
