### ISSUE TITLE
while importing from csv

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#12]
Tiny bug / missing error message: When importing a csv-file and first selecting an Operation the new values should be added to  from the dropdown, then activating the checkbox for "Vorhandene Ressourcen ergänzen", and starting the import, the following error occurs:

main.d1c9efc….js:3 no msg found for key of M with id: "FATAL ERROR - illegal argument combination - operationId and mergeIfExists must not be both truthy"

I suppose the previous selection is not automatically deleted. Works fine if checkbox is deactivated, "Keine Zuordnung" selected from dropdown, and the checkbox then re-activated again. It's not really a problem in any way, just thought I would let you know.

**Comment by danielmarreirosdeoliveira** [comment]
Thx for submitting this. We'll see to fix that quickly

**Comment by danielmarreirosdeoliveira** [comment]
Fixed with https://github.com/dainst/idai-field/commit/1241adea7f586a1fbac026b46c9e21d8bb65bec0 which will be part of the next release. Thx again for reporting.
