### ISSUE TITLE
polylines in map view

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#14]
It is really only a minor inconvenience, but I wanted to let you know: 
When drawing a polyline or selecting a resource with a polyline, the map view zooms on the first vertex of the line and one needs to scroll a lot to see the whole trench again, as it zooms to a level that shows less than a millimeter on the whole screen (assuming one uses coordinates in meters). Maybe it is possible to change this, so that the whole extent of the polyline is seen in map view when selecting the resource? (Similar to the way it is done with polygons.)

(note: I am using the current commit, but it is not a new 'issue'. If I recall correctly this happened in the 2.18 release as well)

**Comment by danielmarreirosdeoliveira** [comment]
I think I see what you mean. We'll have a look at that

**Comment by danielmarreirosdeoliveira** [comment]
Fix comes with the new version next week

**Comment by lsteinmann** [comment]
You are great! Thanks a lot.
