### ISSUE TITLE
Throw error at startup if FieldHub does not have write permissions for files directory

### ISSUE THREAD

**Issue by tkleinke** [dainst/idai-field#149]
Currently FieldHub starts as usual even if no write permissions for the files directory are set. When creating a new project, the CouchDB database and user are created, but not the image directories. Thus, the project page in FieldHub cannot be loaded correctly and file synchronization fails.

FieldHub should check if it has the sufficient write permissions for the files directory on startup and exit with an error message if the check fails.

**Comment by dersmon** [comment]
Possibly best combined with #147.
