### ISSUE TITLE
Folder icons not shown on MacOS

### ISSUE THREAD

**Issue by tkleinke** [dainst/idai-field#150]
On MacOS, the folder icons on the project page are not displayed properly. A possible solution might be replacing the unicode icons with images or using an icon library.

<img width="814" alt="icon" src="https://github.com/dainst/idai-field/assets/5707629/38246afc-2743-4898-8b49-32dec93d1b8b">

**Comment by nilanjan2002** [comment]
Hey there! I'm a beginner, can I fix this issue?

**Comment by dersmon** [comment]
Sure, take your shot and create a pull request. 🙂

**Comment by dersmon** [comment]
Those are the only icons right now, so I would vote for the image based approach instead of adding an additional library.

**Comment by dersmon** [comment]
https://github.com/dainst/idai-field/blob/master/server/lib/field_hub_web/live/project_show_live.html.heex#L111-L116

**Comment by dersmon** [comment]
Hi  @nilanjan2002! Did you already work on this issue? Otherwise I would reassign the issue to a new colleague.

**Comment by the-last-pastafarian** [comment]
The unicode has been replaced by png images, still need to be tested on MacOS.
