### ISSUE TITLE
Spring cleaning: Unused Imports

### ISSUE THREAD

**Issue by t-book** [dainst/idai-field#17]
I think those imports are not used. If a cleanup looks useful I can open a PR

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/backup/backup-creation.component.ts#L3

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/backup/backup-creation.component.ts#L11

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/docedit/core/forms/dimension.component.ts#L3

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/image/overview/link-modal.component.ts#L5

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/messages/md-internal.ts#L1

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/messages/md.ts#L1

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/navbar/navbar.component.ts#L5

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/navbar/projects.component.ts#L2

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/navbar/projects.component.ts#L4

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/components/navbar/taskbar-update.component.ts#L2

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/core/configuration/boot/configuration-definition.ts#L1

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/core/docedit/document-holder.ts#L15

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/core/import/import/process/import-validator.ts#L7

**Comment by t-book** [comment]
I see no problem. But just for the record (regex to often fools me :))

https://github.com/dainst/idai-field/blob/2243a4eb04e081c17ac06fdd105d49ca01591e56/src/app/core/settings/settings-service.ts#L239

 The escape sequence '\\.' is not needed for period _in a character class_. `[0-9a-z\.-]` and `[0-9a-z.-]` will be the same

**Comment by danielmarreirosdeoliveira** [comment]
Thx. I fixed that just now
