### ISSUE TITLE
Enforce project key maximum of 30 characters

### ISSUE THREAD

**Issue by dersmon** [dainst/idai-field#177]
Currently FieldHub does not cap the character length at 30 for newly created projects. Projects created with a longer key can not be initialized in Field Desktop.

See https://github.com/dainst/idai-field/blob/master/desktop/src/app/model/project-identifier-validation.ts#L10

**Comment by PrabalParihar** [comment]
@dersmon 
I am interested in this issue 
Would you be able to assign this issue to me so I can investigate it further?

**Comment by dersmon** [comment]
Hi @PrabalParihar! Did you already work on the issue? Otherwise I would reassign the issue to a new colleague of mine.

**Comment by PrabalParihar** [comment]
Hi there!  I'm currently tied up with some urgent work. I haven't had a
chance to address the issue yet. Please feel free to reassign it to your
new colleague, and I'm sure they'll be able to assist with it. If you have
any questions or need any information from me to help with the transition,
don't hesitate to ask. Thanks!
