### ISSUE TITLE
Show last database update in FieldHub's project overview

### ISSUE THREAD

**Issue by dersmon** [dainst/idai-field#181]
CouchDB provides a [GET /{db}/_changes](https://docs.couchdb.org/en/stable/api/database/changes.html) endpoint. The FieldHub's CouchService should be extended accordingly.

**Comment by dersmon** [comment]
Should be displayed here: https://github.com/dainst/idai-field/blob/master/server/lib/field_hub_web/live/project_show_live.html.heex#L50

`@stats` is evaluated here: https://github.com/dainst/idai-field/blob/master/server/lib/field_hub_web/live/project_show_live.ex#L57

**Comment by the-last-pastafarian** [comment]
The functions created have to be improved. Indeed they don't allow to obtain every time the last modification. In addition, when a document is deleted, it is not possible to know when the delete took place or who made it.

**Comment by dersmon** [comment]
See #201.
