### ISSUE TITLE
project configuration: editor not closing after editing a specific field

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#184]
Hi people, I noticed the following hyper-specific bug in the project configuration editor: 

In the milet-configuration, there is a category called "Quantification_B" and it has the (default) "period" field. If I try to edit it and make any change there, I am not allowed to save it. However, I can also not close the editing modal again and have to restart the app to continue. I tried a bunch of other categories and fields (but not *everything*), and as far as I can tell that only happens with this specific resource category and field.
The developer console shows the following after opening the editing dialog and making a change: 
"ERROR Error: illegal argument in 'tsfun|equal' - Associative expected" [etc. etc.]
But it repeats that a lot, so I am not sure if it really has anything to do with that (tiny) problem.

I do not depend on fixing this. I only noticed because I was wondering if I could change it from a dropdown range to a regular dropdown, but I would have to clean too much data and re-import it into a new field, which I am not prepared to do anyway. Also, since that is the only way I can reproduce it, that probably affects almost no-one. I still thought I'd let you know since it is somewhat unexpected behaviour.

**Comment by tkleinke** [comment]
Hi Lisa, I was able to reproduce and fix a bug that caused the behaviour you described when trying to hide default fields (like "period") of custom categories. Everything else (changing valuelist, labels etc.) seems to work as expected, is that correct?

**Comment by lsteinmann** [comment]
Thanks a lot! Everything else works as expected, as far as I can see. I tried changing valuelists now and have on occasion changed or added labels, and have never encountered a problem there.

**Comment by tkleinke** [comment]
Great, I'm closing the issue then. The bugfix will be released with the next version.
