### ISSUE TITLE
field-web: sorting order of resource lists seems to be random

### ISSUE THREAD

**Issue by marcelriedel** [dainst/idai-field#188]
Hi,

as just discussed, the items of the resource lists (e.g. trenches) in field-web (test) are not alphabetically ordered by identifier. It should be the same as in the desktop client.

Greetings,
Marcel

**Comment by tkleinke** [comment]
The order itself is correct, but there was a bug that caused resources to be loaded multiple times when scrolling. This made the resource order look random. I have just fixed the bug, thanks for reporting!

**Comment by marcelriedel** [comment]
Thank you!
