### ISSUE TITLE
Created field cannot be deleted

### ISSUE THREAD

**Issue by archaeosmith** [dainst/idai-field#206]
Using the newest version of Field Desktop 3.4.1, a field created by our project ("gird-i_begum:dimensionElevationTop") cannot be deleted. Trying to delete results in an "unknown error". The Developer Console shows the message:

No message template found for key: "configuration/buildProjectCategories/noValuelistProvided,Gird-i_begum:Locus,gird-i_begum:dimensionElevationTop"

The logfile for this message is attached.

Thank you in advance.
[-1720711584806.log](https://github.com/user-attachments/files/16180586/-1720711584806.log)

**Comment by tkleinke** [comment]
Could you please export your configuration in the project configuration editor (via menu "Project configuration" -> "Export configuration...") and either attach the file to this issue or send it to [idai.field@dainst.de](mailto:idai.field@dainst.de)? Then we could investigate further.

**Comment by archaeosmith** [comment]
I have sent the configuration file to idai.field@dainst.de.

**Comment by tkleinke** [comment]
The bug will be fixed in the next version, I'm closing this issue now. I've sent you an updated version of the configuration file as a quick fix via mail.
