### ISSUE TITLE
rework the shapefile / shp export to avoid Java

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#233]
there may be newer libraries available that can do the trick without using java. this will be better, since people wont have to install jdk on their system to use the export. 
maybe checkout [bugra9/gdal3.js](https://github.com/bugra9/gdal3.js/) or [mapbox/shp-write](https://github.com/mapbox/shp-write) ?  
converting the GeoJSON to shp in the app would be enough.

**Comment by tkleinke** [comment]
Shapefile import/export now uses https://github.com/bugra9/gdal3.js/
