### ISSUE TITLE
Qgis not recognizing Geojson from idaifield export

### ISSUE THREAD

**Issue by maxhaibt** [dainst/idai-field#5]
Qgis needs this header in a geojson
{
"type": "FeatureCollection",
"name": "WES_sampleareas150cm_session_24022019_K18_wgs84_utm38n",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32638" } },

While idai.field does not specify CRS

{
  "type": "FeatureCollection",

**Comment by benducke** [comment]
That's both a bug in QGIS and a big mess in the GeoJSON specification. There used to be a "crs" member in GeoJSON, but it was removed in the currently valid specification (RFC7946, see B.1: https://tools.ietf.org/html/rfc7946). According to the *draft* specification (there are two, one draft 5 and one draft 6; lord knows which one is relevant now), it will back, but *optional*: http://wiki.geojson.org/GeoJSON_draft_version_6. To make the chaos complete, the online specs also have the "crs" element: https://geojson.org/geojson-spec.html. However, in all cases it is optional, so QGIS should read GeoJSON without a "crs" element if its GeoJSON parser behaved correctly. You could file a bug report with the QGIS project, but I think it would be easier to have iDAI.field produce GeoJSON with a "crs" element.

**Comment by benducke** [comment]
Which version of QGIS are you using?
QGIS 3.4.12 reads GeoJSON files that have no "crs" or "name" elements without problems.
