### ISSUE TITLE
can't add new supercategory

### ISSUE THREAD

**Issue by nafergo** [dainst/idai-field#65]
using linux and can't really add new supercategory. There's no green button to create new supercategory.

![Screenshot from 2022-05-10 00-41-50](https://user-images.githubusercontent.com/6432502/167515714-fa102745-de39-425e-93b3-1299f83dc549.png)

**Comment by tkleinke** [comment]
It's currently not possible to create custom supercategories in the configuration editor. The option "Add supercategory" is only for adding one of the predefined supercategories from the Field configuration library. We might add the feature to create new supercategories in the future, but currently this is one of the limitations of the editor.

If you want to know more about the capabilities of the configuration editor, please also have a look at the [manual](https://github.com/dainst/idai-field/blob/master/desktop/src/manual/manual.en.md#project-configuration).
