### ISSUE TITLE
can't find info about catalogs

### ISSUE THREAD

**Issue by nafergo** [dainst/idai-field#67]
can't find info about catalogs on the manual. Any guidance would be useful.
ty

**Comment by tkleinke** [comment]
The manual is not complete yet and will be expanded in future versions. Currently, catalogs are intended solely for managing find types. You can add type catalogs by switching to type management (via the menu "Tools" -> "Type management"). Here you can create new catalogs via the plus button and add new types to existing catalogs (also via plus button after switching into the context of the catalog). When editing a find resource, you can select a type via the field "Typological classification" (in the group "Identification" per default).
Type catalogs can also be exported and imported to other projects from the export/import menus. When exporting a catalog, all images linked to the catalog resource or type resources within the catalog are also exported. If you have any more questions, feel free to ask.
