### ISSUE TITLE
export csv does not select by operation

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#70]
Hey guys, 
when I export a csv, and select the "Kontext"/Operation to export from, the client still exports all resources from the Category selected below. (Edit: I mean, the whole list of resources of that type present in the project, it does not actually select by operation.)
Have a great week and thanks for all the great work!

**Comment by tkleinke** [comment]
Yes, you're right, the context selection didn't work as expected. Will be fixed with the upcoming patch, thanks for reporting!
